# Kalo YAML Configuration

stores:
  KA_MO_YAML:
    format: "KA:MO1:YAML1"
    type: "localFileSystem"
    path: "$KA_MO_YAML_PATH"
  KA_MO_PSQL:
    format: "KA:MO1:PSQL1"
    type: "localFileSystem"
    path: "$KA_MO_PSQL_PATH"
  KA_MO_TS:
    format: "KA:MO1:TS1"
    type: "localFileSystem"
    path: "$KA_MO_TS_PATH"
  KA_MO_GO:
    format: "KA:MO1:GO1"
    type: "localFileSystem"
    path: "$KA_MO_GO_PATH"

config:
  "@kalo-build/plugin-morphe-psql-types":
    structures:
      "Schema": "public"
      "UseBigSerial": false
      "EnablePersistence": true

pipelines:
  compile:
    - stage: "psql-types"
      steps:
        - "plugin: @kalo-build/plugin-morphe-psql-types"
    - stage: "go-struct"
      steps:
        - "plugin: @kalo-build/plugin-morphe-go-struct"
    - stage: "ts-types"
      steps:
        - "plugin: @kalo-build/plugin-morphe-ts-types"

plugins:
  "@kalo-build/plugin-morphe-psql-types":
    version: "v1.0.0"
    input:
      format: "KA:MO1:YAML1"
      store: "KA_MO_YAML"
    output:
      format: "KA:MO1:PSQL1"
      store: "KA_MO_PSQL"
  
  "@kalo-build/plugin-morphe-ts-types":
    version: "v1.0.0"
    input:
      format: "KA:MO1:YAML1"
      store: "KA_MO_YAML"
    output:
      format: "KA:MO1:TS1"
      store: "KA_MO_TS"
  
  "@kalo-build/plugin-morphe-go-struct":
    version: "v1.0.0"
    input:
      format: "KA:MO1:YAML1"
      store: "KA_MO_YAML"
    output:
      format: "KA:MO1:GO1"
      store: "KA_MO_GO"